# Generated by Django 3.2.16 on 2022-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
