# Generated by Django 3.2.16 on 2023-01-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20221231_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='auth',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
