# Generated by Django 3.2.16 on 2023-01-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_voter_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='vote_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
