# Generated by Django 3.2.16 on 2023-01-07 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20230107_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.division'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.division'),
        ),
    ]
