# Generated by Django 3.2.16 on 2023-01-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20230107_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
